CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -pedantic -O2

TARGETS = challenge1

all: $(TARGETS)

challenge1: challenge1.cpp
	$(CXX) $(CXXFLAGS) -o challenge1 challenge1.cpp

clean:
	rm -f $(TARGETS)